### PR TITLE
fix(ci): build packages/cli in the unit job so CLI bin-spawn tests pass

### PR DESCRIPTION
**Pull request by buremba**
Closes the gap from [[ci-build-order-workspace-pkgs]]: the unit job pre-build step builds core/connector-sdk/embeddings/connector-worker but not cli, so packages/cli/src/__tests__/cli-ux.test.ts fails in CI with 'Cannot find module ../dist/index.js' from bin/lobu.js while passing locally.

Discovered after PR #1117 (submodule pointer bump) was held in OPEN state by failing unit checks — which in turn meant prod was running with a half-rolled image set (worker+embeddings on the #1116 tag, app on the older #1114 tag), blocking the CORS fix from reaching users.

Tests: regression test from PR #1114 should now pass in the unit job. No new tests added — this is purely a CI build-order fix mirroring what cli-smoke / sdk-e2e already do (`make build-packages`).

---
<a href="https://app.blacksmith.sh/lobu-ai/codesmith/lobu/pr/1118"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1782568192&installation_id=136316292&pr_number=1118&repository=lobu-ai%2Flobu&return_to=https%3A%2F%2Fgithub.com%2Flobu-ai%2Flobu%2Fpull%2F1118&signature=8af81419aa10d24c3c082485ca231d6eecb50b4e7e53cd9ad40433217fbd97a6"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>@codesmith</code> with what you need. Autofix is disabled.</sup>

## Summary by CodeRabbit

* **Tests**
  * Fixed CLI test infrastructure to ensure consistent behavior across local and CI environments.

* **Chores**
  * Updated subproject dependency reference.

[Review Change Stack](https://app.coderabbit.ai/change-stack/lobu-ai/lobu/pull/1118?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

**Comment by buremba** [comment]
Superseded by #1126 which landed the same CI fix + owletto pointer bump.
