### PR TITLE
fix(server): truthful vitest exit codes, fail-closed CI gate, and the 8 red integration tests

### LINKED ISSUE #1216: main integration job: 8 failing tests, and failures don't always fail the workflow
Found while shipping 11.1.0: the `integration` job on main has 8 failing tests across 5 files, and worse, the failure doesn't reliably fail the workflow. These are two separate problems.

## 1. Failures don't always propagate

Run [27363592280](https://github.com/lobu-ai/lobu/actions/runs/27363592280) (commit c2bdde52) concluded **success** while its integration log plainly shows:

```
Test Files  5 failed | 114 passed (119)
⎯⎯⎯ Failed Tests 8 ⎯⎯⎯
```

The very next commit's run [27364008324](https://github.com/lobu-ai/lobu/actions/runs/27364008324) (c8294bb6) has the **identical** 8 failures and concluded failure. Same tests, different workflow conclusion, so the vitest exit code is getting swallowed nondeterministically somewhere in the job (pipe without pipefail, a tee, a retry step, whatever it is). A green main with 8 failing tests is worse than a red main; this is the half to fix first.

## 2. The 8 failures themselves

All of them predate the #1209-#1214 merges (they're in the c2bdde52 "green" run too):

- `src/__tests__/server-lifecycle.test.ts` > "shuts down in the documented order": the source-level contract greps for the literal `httpServer.close();`, but #1191 rewrote shutdown to `await safe("httpServer.close", ... httpServer.close(() => done()))` without updating the needle. Test is stale, not the code.
- `src/auth/__tests__/config.baseline.integration.test.ts`: 4 failures in the login-provider baseline (e.g. "hides providers whose credentials are absent" gets `true` where it expects `undefined`). Probably fallout from the #1183 global login baseline work, or env leakage in the runner.
- `src/__tests__/integration/auth/anonymous-device-registration.test.ts` > "does NOT register in cloud mode"
- `src/__tests__/integration/connectors/postgres-sync-cloud-gate.test.ts` > cloud gate expects 200, gets 401
- `src/__tests__/integration/watchers/rollup-window-id-race.test.ts` > concurrent rollup completion race

The last three are all `LOBU_CLOUD_MODE` / env-sensitive tests, which smells like shared env pollution between test files rather than three independent regressions, but I haven't bisected them.

Suggested order: fix the exit-code propagation, then the stale server-lifecycle needle (one-liner), then bisect the env-sensitive cluster.

### PR DESCRIPTION
**Pull request by buremba**
Fixes #1216

## Part A — why CI went green over 8 failures

`node .../vitest run` has no pipe, so the shell wasn't swallowing anything — **vitest's own process exited 0**. Traced with a `process.exit` interceptor:

```
[trace-exit pid=… argv1=.bin/vitest] process.exit(0) called; process.exitCode=1
    at processTicksAndRejections   ← bare callback, zero user frames
```

Root cause chain:
1. The vitest globalSetup statically imports `embedded-postgres` (test backend), which **at module load** registers `async-exit-hook` — in the **main vitest process**.
2. `async-exit-hook` hooks `beforeExit` with code 0. After a failed run, vitest sets `process.exitCode = 1` and lets the loop drain; Node emits `beforeExit`; the hook runs and then `process.nextTick(process.exit.bind(null, 0))` overwrites the failure with exit 0.
3. Nondeterminism between runs 27363592280 (silent green) and 27364008324 (correct red): `beforeExit` only fires when the loop fully drains. A straggling handle means vitest's teardown-timeout `process.exit()` (no-arg → uses exitCode=1) wins instead.

Reproduced deterministically in a minimal repro: `import 'embedded-postgres'` in a globalSetup flips a failing run's exit code from 1 to 0.

**Fix (two layers, both validated):**
- Root cause: `embedded-postgres-backend.ts` unhooks async-exit-hook's `beforeExit` (and its broken `exit` hook, which calls the async cleanup without a `done` callback and throws an unhandled `done is not a function` rejection on every *clean* run once the clobber is gone). Signal hooks stay; `teardown()` stops clusters explicitly.
- Fail-closed CI gate: the vitest step now also writes `--reporter=json`, and `scripts/assert-vitest-report-clean.mjs` independently asserts `success && 0 failed && ≥1 test ran`, failing also when the report is missing/unparseable (crashed run). The gate no longer depends on every future import staying side-effect-free.

## Part B — per-test root causes

| Test | Verdict | Root cause |
|---|---|---|
| server-lifecycle "shuts down in documented order" | stale test | #1191 rewrote `httpServer.close();` into `safe("httpServer.close", …)` bounded drain; needle updated to the step label (main fixed this concurrently in #1218 — kept main's hunk on rebase). All other needles in the block verified against current source. |
| config.baseline.integration ×4 | broken test env | Test pointed `CONNECTOR_CATALOG_URIS` at `packages/server/dist/connectors`, which the integration job (and any fresh checkout) **never builds** → empty catalog → empty login baseline. Now falls back to `packages/connectors/src` (manifest-miss compile path, ~10s, same catalog→collect→merge→credential-gate pipeline). Not a prod bug. |
| anonymous-device-registration "cloud mode strict" | stale test | #1192 (security audit) made anonymous workers-API access **fail closed with 401** under `LOBU_CLOUD_MODE`; the test predates it (#1017) and expected a degraded 200. Now asserts 401 + no registration — strictly stronger than the test's original intent. |
| postgres-sync-cloud-gate "execution-time gate" | stale test | Same #1192 gate rejects the anonymous poll before it reaches the code under test. The poll now authenticates as a trusted fleet worker (`WORKER_API_TOKEN` via the test env override) so it exercises the execution-time cloud gate in `pollWorkerJob`. |
| rollup-window-id-race | 🚨 **REAL PROD BUG** | `complete_window`'s rollup INSERT bound a bare JS array into `source_window_ids integer[]`. The prod pool runs `fetch_types: false`, so postgres.js can't infer the element type and ships `"5,6"` → PG `malformed array literal` → **every rollup completion fails in prod** (same bug class as the 12-day watcher wedge fixed in #1046; the test harness was deliberately aligned to prod options there so this surfaces). Fixed with the established `pgBigintArray(...)::int[]` literal idiom. |

None of the 8 were cross-file env pollution — all reproduced when running the 5 files alone, and 6-7 reproduced per-file in isolation.

## Validation

- Full `vitest run` (packages/server, Node 22, embedded PG): **122 files / 1031-1032 passed, 0 failed — three times** (twice pre-rebase, once post-rebase onto current main), guard `OK` each time.
- Part A demonstration: injected a deliberately failing test → vitest exits **1** (root-cause fix) and the JSON guard exits **1** independently; guard also exits 1 on a missing report; green run → vitest 0 + guard OK. Injection reverted.
- `bun test src/gateway/__tests__` and `bun test src/lobu/__tests__ src/workspace/__tests__`: 12 + 5 failures locally, but **byte-identical failure sets on a clean origin/main worktree with the same DATABASE_URL** (and green in actual CI) → pre-existing local-env issues, untouched by this PR.
- `bunx tsc --noEmit` clean in packages/server.

---
<a href="https://app.blacksmith.sh/lobu-ai/codesmith/lobu/pr/1220"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1783809917&installation_id=136316292&pr_number=1220&repository=lobu-ai%2Flobu&return_to=https%3A%2F%2Fgithub.com%2Flobu-ai%2Flobu%2Fpull%2F1220&signature=7863d13c753f1bd04e7c4bc1e92462de4c9e171775843d374bd64eb95f9e7500"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>/codesmith</code> with what you need. Autofix is disabled.</sup>

## Summary by CodeRabbit

* **Tests**
  * Enhanced CI reliability with stricter test failure detection in Vitest JSON reports
  * Improved authentication and cloud-mode security test validations
  * Refactored shared test utilities to reduce redundancy across integration test suites
  * Fixed test isolation and determinism issues in content visibility and configuration tests

* **Bug Fixes**
  * Corrected database parameter handling for integer arrays in admin tools

### CODE REVIEW

**Comment by buremba** [comment]
**bug_free 82, simplicity 88, slop 0, bugs 0, 0 blockers**

Typecheck/unit passed; integration exit 1 appears env: Node v26 lacks isolated-vm and PUBLIC_WEB_URL=localhost affects public-origin/pages expectations. Ran git diff/check and synthetic assert-vitest-report-clean pass/fail probes OK.

<details><summary>Full verdict JSON</summary>

```json
{
  "bug_free_confidence": 82,
  "bugs": 0,
  "slop": 0,
  "simplicity": 88,
  "blockers": [],
  "change_type": "fix",
  "behavior_change_risk": "low",
  "tests_adequate": true,
  "suggested_fixes": [],
  "notes": "Typecheck/unit passed; integration exit 1 appears env: Node v26 lacks isolated-vm and PUBLIC_WEB_URL=localhost affects public-origin/pages expectations. Ran git diff/check and synthetic assert-vitest-report-clean pass/fail probes OK.",
  "categories": {
    "src": 34,
    "tests": 309,
    "docs": 0,
    "config": 0,
    "deps": 0,
    "migrations": 0,
    "ci": 69,
    "generated": 0
  }
}
```

</details>

_Local review gate — branch protection can require the `pi-review` commit status. See `docs/REVIEW_SCHEMA.md`._

**Comment by buremba** [comment]
Correction + follow-up commit (b4abbad0): the PR body's claim that the bun lobu-suite failures were "pre-existing, green in real CI" was based on a false baseline — that CI step had been skipped on every run since #1212 (the vitest step failed first), so those tests had never run in real CI.

Root cause: bun's `mock.module` is process-global and module evaluation is cached — `agent-routes.js` stayed bound to the FIRST test file's mock closures, so `agent-routes-rest-platform.test.ts` authenticated under `agent-routes-apply.test.ts`'s auth stash (wrong org) and 404'd whenever both files ran in one process. Fixed with a shared mutable stash helper (`src/lobu/__tests__/helpers/route-test-mocks.ts`) that installs the mocks once; both files set per-test values in `beforeEach`.

Also in the same commit, two more hermeticity fixes: `config.baseline.integration.test.ts` now scrubs ambient `GITHUB_*`/`GOOGLE_*`/… credentials (`resolveLoginProviderCredentials` falls back to `process.env`), and the hosted-UI-fallback tests (`url-builder`, `get-content-visibility`) pin `hasLocalFrontend()` via a new test seam — they implicitly required no `packages/owletto/dist` on the machine, which any owletto build (e.g. `make review`) violates.

Validated: combined `bun test src/lobu/__tests__ src/workspace/__tests__` 35/0; each file green alone; full vitest 122 files / 0 failed (with the owletto dist present); `config.baseline` green both with and without ambient `GITHUB_CLIENT_ID` set; `tsc --noEmit` clean.
